LeagueManagerPost/LeagueManagerPost/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LeagueManagerPost.Models;

namespace LeagueManagerPost.Controllers
{
    public class GamesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Games
        //public ActionResult Index()
        //{
        //    var games = db.Games.Include(g => g.AwayTeam).Include(g => g.HomeTeam);
        //    return View(games.ToList());
        //}

        public ViewResult Index(int? id, string sortOrder, string searchString)
        {
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.TimeSortParm = sortOrder == "Time" ? "time_desc" : "Time";
            ViewBag.LocationSortParm = String.IsNullOrEmpty(sortOrder) ? "location_" : "";
            ViewBag.HomeTeamSortParm = String.IsNullOrEmpty(sortOrder) ? "homeTeam_" : "";
            ViewBag.AwayTeamSortParm = String.IsNullOrEmpty(sortOrder) ? "awayTeam_" : "";

            var games = from s in db.Games.Include(s => s.HomeTeam).Include(s => s.AwayTeam)
                        select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                games = games.Where(s => s.HomeTeam.Name.Contains(searchString)
                                       || s.AwayTeam.Name.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "Date":
                    games = games.OrderBy(s => s.Date);
                    break;
                case "Time":
                    games = games.OrderBy(s => s.Time);
                    break;
                case "location_":
                    games = games.OrderBy(s => s.Location);
                    break;
                case "homeTeam_":
                    games = games.OrderBy(s => s.HomeTeam.Name);
                    break;
                case "awayTeam_":
                    games = games.OrderBy(s => s.AwayTeam.Name);
                    break;
                default:
                    games = games.OrderBy(s => s.Date);
                    break;
            }

            return View(games.ToList());
        }

        // GET: Games/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Include(g => g.AwayTeam)
                                .Include(g => g.HomeTeam)
                                .SingleOrDefault(x => x.Id == id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // GET: Games/Create
        public ActionResult Create()
        {
            ViewBag.AwayTeamId = new SelectList(db.Teams, "Id", "Name");
            ViewBag.HomeTeamId = new SelectList(db.Teams, "Id", "Name");
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Date,Time,Location,HomeTeamId,AwayTeamId")] Game game)
        {
            //if (ModelState.IsValid)
            //{

            game.HomeTeam = db.Teams.Single(t => t.Id == game.HomeTeamId);
            game.AwayTeam = db.Teams.Single(t => t.Id == game.AwayTeamId);
            

            #region ErrorChecking
            // Home team can't be the same as away team
            if (game.HomeTeam == game.AwayTeam)
            {
                return RedirectToAction("Error", "Home");
            }

            // Very overly complicated if statement
            // Each team can only have one game per day
            // I'm not completely sure if this works right
            foreach (var g in db.Games)
            {
                if ((g.HomeTeam == game.HomeTeam) && (g.Date == game.Date) ||
                    (g.HomeTeam == game.AwayTeam) && (g.Date ==game.Date) ||
                    (g.AwayTeam == game.HomeTeam) && (g.Date == game.Date) ||
                    (g.AwayTeam == game.AwayTeam) && (g.Date == game.Date))
                {
                    return RedirectToAction("SameDayError", "Home");
                }
            }

            //// All of the referees must be different people
            //if (game.Referee == game.SecondReferee ||
            //    game.Referee == game.ThirdReferee ||
            //    game.ThirdReferee == game.SecondReferee)
            //{
            //    return RedirectToAction("RefereeError", "Home");
            //}
            #endregion

            #region EventCreation
            // Adds event to calendar when a game is created
            string gameTime = game.Time.ToShortTimeString();
            string awayTeamString = game.AwayTeam.Name + " (" + game.AwayTeam.Wins + "-" + game.AwayTeam.Losses + ")";
            string homeTeamString = game.HomeTeam.Name + " (" + game.HomeTeam.Wins + "-" + game.HomeTeam.Losses + ")";
            string gameDescription = "The " + awayTeamString + " are playing the " + homeTeamString
                                        + " at the " + game.Location + ". Start time is " + gameTime + ". ";


            

            var eve = new Events
            {
                Subject = game.AwayTeam.Name + " @ " + game.HomeTeam.Name,
                Start = game.Date,
                IsFullDay = true,
                Description = gameDescription,
                ThemeColor = "Blue",
                Event = game.Id


            };
            db.Events.Add(eve);
            #endregion

            db.Games.Add(game);
                db.SaveChanges();
                return RedirectToAction("Index");
            //}

            //ViewBag.AwayTeamId = new SelectList(db.Teams, "Id", "Name", game.AwayTeamId);
            //ViewBag.HomeTeamId = new SelectList(db.Teams, "Id", "Name", game.HomeTeamId);
            //return View(game);
        }

        // GET: Games/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            ViewBag.AwayTeamId = new SelectList(db.Teams, "Id", "Name", game.AwayTeamId);
            ViewBag.HomeTeamId = new SelectList(db.Teams, "Id", "Name", game.HomeTeamId);
            return View(game);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Date,Time,Location,HomeTeamId,AwayTeamId")] Game game)
        {
            if (ModelState.IsValid)
            {
                db.Entry(game).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AwayTeamId = new SelectList(db.Teams, "Id", "Name", game.AwayTeamId);
            ViewBag.HomeTeamId = new SelectList(db.Teams, "Id", "Name", game.HomeTeamId);
            return View(game);
        }

        // GET: Games/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Include(g => g.AwayTeam)
                                .Include(g => g.HomeTeam)
                                .SingleOrDefault(x => x.Id == id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Game game = db.Games.Find(id);
            db.Games.Remove(game);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LeagueManagerPost/LeagueManagerPost/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LeagueManagerPost.Models;

namespace LeagueManagerPost.Controllers
{
    public class TeamsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private readonly Repository _repo = new Repository();

        // GET: Teams
        //public ActionResult Index()
        //{
        //    return View(db.Teams.ToList());
        //}

        public ViewResult Index(string sortOrder, string searchString)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_" : "";
            ViewBag.CoachSortParm = String.IsNullOrEmpty(sortOrder) ? "coach_" : "";
            ViewBag.WinsSortParm = String.IsNullOrEmpty(sortOrder) ? "wins_" : "";
            ViewBag.LossesSortParm = String.IsNullOrEmpty(sortOrder) ? "losses_" : "";

            var teams = from s in db.Teams
                        select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                teams = teams.Where(s => s.Name.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_":
                    teams = teams.OrderBy(s => s.Name);
                    break;
                case "coach_":
                    teams = teams.OrderBy(s => s.Coach);
                    break;
                case "wins_":
                    teams = teams.OrderByDescending(s => s.Wins);
                    break;
                case "losses_":
                    teams = teams.OrderByDescending(s => s.Losses);
                    break;
                default:
                    teams = teams.OrderByDescending(s => s.Wins);
                    break;
            }

            return View(teams.ToList());
        }

        // GET: Teams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Team team = db.Teams.Find(id);
            var team = _repo.GetTeamWithPlayers(id.Value);
            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        // GET: Teams/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Teams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Coach,Wins,Losses")] Team team)
        {
            if (ModelState.IsValid)
            {
                db.Teams.Add(team);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(team);
        }

        // GET: Teams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Team team = db.Teams.Find(id);
            var team = _repo.GetTeamWithPlayers(id.Value);
            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        // POST: Teams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Coach,Wins,Losses")] Team team)
        {
            if (ModelState.IsValid)
            {
                db.Entry(team).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(team);
        }

        // GET: Teams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Team team = db.Teams.Find(id);
            if (team == null)
            {
                return HttpNotFound();
            }
            return View(team);
        }

        // POST: Teams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Team team = db.Teams.Find(id);
            db.Teams.Remove(team);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

LeagueManagerPost/LeagueManagerPost/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Mukta+Mahee:400,800|Oswald:400,600|PT+Sans:400,700" rel="stylesheet">
    <title>League Manager 2019 - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("League Manager 2019", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle g" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Games
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @*@if (User.IsInRole("Admin"))
                            {
                                @Html.ActionLink("Create Game", "Create", "Games", null, new { @id = "something" })

                                <div class="dropdown-divider"></div>
                            }*@


                            @Html.ActionLink("Create Game", "Create", "Games", null, new { @id = "something" })
                            <div class="dropdown-divider"></div>
                            @Html.ActionLink("All Games", "Index", "Games")
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Teams
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @*@if (User.IsInRole("Admin"))
                            {
                                @Html.ActionLink("Create Team", "Create", "Teams")
                                <div class="dropdown-divider"></div>
                            }*@


                            @Html.ActionLink("Create Team", "Create", "Teams")
                            <div class="dropdown-divider"></div>
                            @Html.ActionLink("All Teams", "Index", "Teams")
                        </div>
                    </li>

                    @*<li>@Html.ActionLink("Create Game", "Create", "Games")</li>
                    <li>@Html.ActionLink("Create Team", "Create", "Teams")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                    <li>@Html.ActionLink("Calendar", "Events", "Home")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - League Manager</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>